### ISSUE TITLE
Add silkscreen to label solar panels

### ISSUE THREAD

**Issue by matgyver** [M2I-CySat/CySat-SidePanels#2]
Add lettering for all solar panels for easier reference instead of the auto-generated ones by KiCad.

**Comment by matgyver** [comment]
@kellyt-1 and @mkilcoin please get me a list of student names that worked on this satellite.

**Comment by mkilcoin** [comment]
I sent you an email with this information in a document.

**Comment by matgyver** [comment]
Added all information as requested in 3a5c0a4.  Closing issue.
