### ISSUE TITLE
Verify placement on Y+ and check clearance

### ISSUE THREAD

**Issue by matgyver** [M2I-CySat/CySat-SidePanels#3]
Need to double check clearance with solar cells (right up near the edge) and also that the cut-outs are correct.

**Comment by matgyver** [comment]
@kellyt-1 and I checked the cutouts.  The one for the RBF pin is a bit large, but is in the correct location.  At this time I don't think I will reduce the size of the opening as I don't believe it will give us enough board space to make a difference.  However, before closing this issue I will export the boards as STEP files so they can be confirmed in the master solidworks files.

**Comment by matgyver** [comment]
Verified with old boards and all seems to be ok.  @kellyt-1 and @mkilcoin, please double check with the STEP files I added in 3a5c0a4.  If all is good, please close out this issue.

**Comment by kellyt-1** [comment]
(Y+) Cutouts match master SW design, smallest clearance for solar cells near the edge of the board is 0.4 mm. (Y-) Attachment points and cutout for ADCS camera match. (X+/X-) All cutouts match the original SW design.
